# Generated by Django 4.2.1 on 2023-06-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificate',
            new_name='WDCertificate',
        ),
    ]
